// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM65M-TDYe-psG5WNqUrzyuHgwMoqXwVQ',
    appId: '1:523195431607:web:b70a780842a127f7686b32',
    messagingSenderId: '523195431607',
    projectId: 'my-otp-kmj',
    authDomain: 'my-otp-kmj.firebaseapp.com',
    storageBucket: 'my-otp-kmj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCClHl-VtQF2cc-HvPrlZGM7uGwl12uDg4',
    appId: '1:523195431607:android:da4fb9b9df4db5c2686b32',
    messagingSenderId: '523195431607',
    projectId: 'my-otp-kmj',
    storageBucket: 'my-otp-kmj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdvvHaDnDsiMDfAOBHjIReAr7i_zQD5U',
    appId: '1:523195431607:ios:b971596b6d0b8e9d686b32',
    messagingSenderId: '523195431607',
    projectId: 'my-otp-kmj',
    storageBucket: 'my-otp-kmj.firebasestorage.app',
    iosBundleId: 'com.pertamina.kmj.projectOtpKmj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQdvvHaDnDsiMDfAOBHjIReAr7i_zQD5U',
    appId: '1:523195431607:ios:b971596b6d0b8e9d686b32',
    messagingSenderId: '523195431607',
    projectId: 'my-otp-kmj',
    storageBucket: 'my-otp-kmj.firebasestorage.app',
    iosBundleId: 'com.pertamina.kmj.projectOtpKmj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM65M-TDYe-psG5WNqUrzyuHgwMoqXwVQ',
    appId: '1:523195431607:web:b5eb63d3164ed9ca686b32',
    messagingSenderId: '523195431607',
    projectId: 'my-otp-kmj',
    authDomain: 'my-otp-kmj.firebaseapp.com',
    storageBucket: 'my-otp-kmj.firebasestorage.app',
  );

}